//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sourceportal.SAP.Services.AccountHierarchyManageService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sap.com/xi/AP/Common/Global")]
    public partial class StandardFaultMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ExchangeFaultData standardField;
        
        private StandardFaultMessageExtension additionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ExchangeFaultData standard {
            get {
                return this.standardField;
            }
            set {
                this.standardField = value;
                this.RaisePropertyChanged("standard");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public StandardFaultMessageExtension addition {
            get {
                return this.additionField;
            }
            set {
                this.additionField = value;
                this.RaisePropertyChanged("addition");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/Global")]
    public partial class ExchangeFaultData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string faultTextField;
        
        private string faultUrlField;
        
        private ExchangeLogData[] faultDetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string faultText {
            get {
                return this.faultTextField;
            }
            set {
                this.faultTextField = value;
                this.RaisePropertyChanged("faultText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string faultUrl {
            get {
                return this.faultUrlField;
            }
            set {
                this.faultUrlField = value;
                this.RaisePropertyChanged("faultUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("faultDetail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ExchangeLogData[] faultDetail {
            get {
                return this.faultDetailField;
            }
            set {
                this.faultDetailField = value;
                this.RaisePropertyChanged("faultDetail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/Global")]
    public partial class ExchangeLogData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string severityField;
        
        private string textField;
        
        private string urlField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
                this.RaisePropertyChanged("severity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/Global")]
    public partial class StandardFaultMessageExtension : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Log logField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Log Log {
            get {
                return this.logField;
            }
            set {
                this.logField = value;
                this.RaisePropertyChanged("Log");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public partial class Log : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string businessDocumentProcessingResultCodeField;
        
        private string maximumLogItemSeverityCodeField;
        
        private LogItem[] itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=0)]
        public string BusinessDocumentProcessingResultCode {
            get {
                return this.businessDocumentProcessingResultCodeField;
            }
            set {
                this.businessDocumentProcessingResultCodeField = value;
                this.RaisePropertyChanged("BusinessDocumentProcessingResultCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=1)]
        public string MaximumLogItemSeverityCode {
            get {
                return this.maximumLogItemSeverityCodeField;
            }
            set {
                this.maximumLogItemSeverityCodeField = value;
                this.RaisePropertyChanged("MaximumLogItemSeverityCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public LogItem[] Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public partial class LogItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeIDField;
        
        private LogItemCategoryCode categoryCodeField;
        
        private string severityCodeField;
        
        private string referenceObjectNodeSenderTechnicalIDField;
        
        private string referenceMessageElementNameField;
        
        private string noteField;
        
        private string noteTemplateTextField;
        
        private LogItemNotePlaceholderSubstitutionList logItemNotePlaceholderSubstitutionListField;
        
        private string webURIField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=0)]
        public string TypeID {
            get {
                return this.typeIDField;
            }
            set {
                this.typeIDField = value;
                this.RaisePropertyChanged("TypeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public LogItemCategoryCode CategoryCode {
            get {
                return this.categoryCodeField;
            }
            set {
                this.categoryCodeField = value;
                this.RaisePropertyChanged("CategoryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=2)]
        public string SeverityCode {
            get {
                return this.severityCodeField;
            }
            set {
                this.severityCodeField = value;
                this.RaisePropertyChanged("SeverityCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=3)]
        public string ReferenceObjectNodeSenderTechnicalID {
            get {
                return this.referenceObjectNodeSenderTechnicalIDField;
            }
            set {
                this.referenceObjectNodeSenderTechnicalIDField = value;
                this.RaisePropertyChanged("ReferenceObjectNodeSenderTechnicalID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ReferenceMessageElementName {
            get {
                return this.referenceMessageElementNameField;
            }
            set {
                this.referenceMessageElementNameField = value;
                this.RaisePropertyChanged("ReferenceMessageElementName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
                this.RaisePropertyChanged("Note");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string NoteTemplateText {
            get {
                return this.noteTemplateTextField;
            }
            set {
                this.noteTemplateTextField = value;
                this.RaisePropertyChanged("NoteTemplateText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public LogItemNotePlaceholderSubstitutionList LogItemNotePlaceholderSubstitutionList {
            get {
                return this.logItemNotePlaceholderSubstitutionListField;
            }
            set {
                this.logItemNotePlaceholderSubstitutionListField = value;
                this.RaisePropertyChanged("LogItemNotePlaceholderSubstitutionList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI", Order=8)]
        public string WebURI {
            get {
                return this.webURIField;
            }
            set {
                this.webURIField = value;
                this.RaisePropertyChanged("WebURI");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public partial class LogItemCategoryCode : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string listIDField;
        
        private string listVersionIDField;
        
        private string listAgencyIDField;
        
        private string listAgencySchemeIDField;
        
        private AgencyIdentificationCode listAgencySchemeAgencyIDField;
        
        private bool listAgencySchemeAgencyIDFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string listID {
            get {
                return this.listIDField;
            }
            set {
                this.listIDField = value;
                this.RaisePropertyChanged("listID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string listVersionID {
            get {
                return this.listVersionIDField;
            }
            set {
                this.listVersionIDField = value;
                this.RaisePropertyChanged("listVersionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string listAgencyID {
            get {
                return this.listAgencyIDField;
            }
            set {
                this.listAgencyIDField = value;
                this.RaisePropertyChanged("listAgencyID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string listAgencySchemeID {
            get {
                return this.listAgencySchemeIDField;
            }
            set {
                this.listAgencySchemeIDField = value;
                this.RaisePropertyChanged("listAgencySchemeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AgencyIdentificationCode listAgencySchemeAgencyID {
            get {
                return this.listAgencySchemeAgencyIDField;
            }
            set {
                this.listAgencySchemeAgencyIDField = value;
                this.RaisePropertyChanged("listAgencySchemeAgencyID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool listAgencySchemeAgencyIDSpecified {
            get {
                return this.listAgencySchemeAgencyIDFieldSpecified;
            }
            set {
                this.listAgencySchemeAgencyIDFieldSpecified = value;
                this.RaisePropertyChanged("listAgencySchemeAgencyIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/BASIS/Global")]
    public enum AgencyIdentificationCode {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("16")]
        Item16,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("17")]
        Item17,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("84")]
        Item84,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("107")]
        Item107,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("109")]
        Item109,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("112")]
        Item112,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("113")]
        Item113,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("114")]
        Item114,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("116")]
        Item116,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("117")]
        Item117,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("124")]
        Item124,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("130")]
        Item130,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("131")]
        Item131,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("138")]
        Item138,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("142")]
        Item142,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("146")]
        Item146,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("262")]
        Item262,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("296")]
        Item296,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("310")]
        Item310,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public partial class LogItemNotePlaceholderSubstitutionList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string firstPlaceholderIDField;
        
        private string secondPlaceholderIDField;
        
        private string thirdPlaceholderIDField;
        
        private string fourthPlaceholderIDField;
        
        private string firstPlaceholderSubstitutionTextField;
        
        private string secondPlaceholderSubstitutionTextField;
        
        private string thirdPlaceholderSubstitutionTextField;
        
        private string fourthPlaceholderSubstitutionTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=0)]
        public string FirstPlaceholderID {
            get {
                return this.firstPlaceholderIDField;
            }
            set {
                this.firstPlaceholderIDField = value;
                this.RaisePropertyChanged("FirstPlaceholderID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=1)]
        public string SecondPlaceholderID {
            get {
                return this.secondPlaceholderIDField;
            }
            set {
                this.secondPlaceholderIDField = value;
                this.RaisePropertyChanged("SecondPlaceholderID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=2)]
        public string ThirdPlaceholderID {
            get {
                return this.thirdPlaceholderIDField;
            }
            set {
                this.thirdPlaceholderIDField = value;
                this.RaisePropertyChanged("ThirdPlaceholderID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=3)]
        public string FourthPlaceholderID {
            get {
                return this.fourthPlaceholderIDField;
            }
            set {
                this.fourthPlaceholderIDField = value;
                this.RaisePropertyChanged("FourthPlaceholderID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string FirstPlaceholderSubstitutionText {
            get {
                return this.firstPlaceholderSubstitutionTextField;
            }
            set {
                this.firstPlaceholderSubstitutionTextField = value;
                this.RaisePropertyChanged("FirstPlaceholderSubstitutionText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string SecondPlaceholderSubstitutionText {
            get {
                return this.secondPlaceholderSubstitutionTextField;
            }
            set {
                this.secondPlaceholderSubstitutionTextField = value;
                this.RaisePropertyChanged("SecondPlaceholderSubstitutionText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ThirdPlaceholderSubstitutionText {
            get {
                return this.thirdPlaceholderSubstitutionTextField;
            }
            set {
                this.thirdPlaceholderSubstitutionTextField = value;
                this.RaisePropertyChanged("ThirdPlaceholderSubstitutionText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string FourthPlaceholderSubstitutionText {
            get {
                return this.fourthPlaceholderSubstitutionTextField;
            }
            set {
                this.fourthPlaceholderSubstitutionTextField = value;
                this.RaisePropertyChanged("FourthPlaceholderSubstitutionText");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/A1S/Global")]
    public partial class BusinessPartnerHierarchyMaintainConfirmation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BusinessPartnerHierarchyID idField;
        
        private UUID uUIDField;
        
        private string referenceObjectNodeSenderTechnicalIDField;
        
        private string changeStateIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public BusinessPartnerHierarchyID ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public UUID UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
                this.RaisePropertyChanged("UUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string ReferenceObjectNodeSenderTechnicalID {
            get {
                return this.referenceObjectNodeSenderTechnicalIDField;
            }
            set {
                this.referenceObjectNodeSenderTechnicalIDField = value;
                this.RaisePropertyChanged("ReferenceObjectNodeSenderTechnicalID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string ChangeStateID {
            get {
                return this.changeStateIDField;
            }
            set {
                this.changeStateIDField = value;
                this.RaisePropertyChanged("ChangeStateID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public partial class BusinessPartnerHierarchyID : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string schemeIDField;
        
        private string schemeAgencyIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeID {
            get {
                return this.schemeIDField;
            }
            set {
                this.schemeIDField = value;
                this.RaisePropertyChanged("schemeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeAgencyID {
            get {
                return this.schemeAgencyIDField;
            }
            set {
                this.schemeAgencyIDField = value;
                this.RaisePropertyChanged("schemeAgencyID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public partial class UUID : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string schemeIDField;
        
        private string schemeAgencyIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeID {
            get {
                return this.schemeIDField;
            }
            set {
                this.schemeIDField = value;
                this.RaisePropertyChanged("schemeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeAgencyID {
            get {
                return this.schemeAgencyIDField;
            }
            set {
                this.schemeAgencyIDField = value;
                this.RaisePropertyChanged("schemeAgencyID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/A1S/Global")]
    public partial class BusinessPartnerHierarchyMaintainConfirmationMessage_sync : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BusinessPartnerHierarchyMaintainConfirmation[] businessPartnerHierarchyField;
        
        private Log logField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BusinessPartnerHierarchy", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public BusinessPartnerHierarchyMaintainConfirmation[] BusinessPartnerHierarchy {
            get {
                return this.businessPartnerHierarchyField;
            }
            set {
                this.businessPartnerHierarchyField = value;
                this.RaisePropertyChanged("BusinessPartnerHierarchy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Log Log {
            get {
                return this.logField;
            }
            set {
                this.logField = value;
                this.RaisePropertyChanged("Log");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public partial class DistributionChannelCode : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string listIDField;
        
        private string listAgencyIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string listID {
            get {
                return this.listIDField;
            }
            set {
                this.listIDField = value;
                this.RaisePropertyChanged("listID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string listAgencyID {
            get {
                return this.listAgencyIDField;
            }
            set {
                this.listAgencyIDField = value;
                this.RaisePropertyChanged("listAgencyID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/A1S/Global")]
    public partial class BusinessPartnerHierarchyMaintainRequestGroupBusinessArea : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string objectNodeSenderTechnicalIDField;
        
        private UUID salesOrganisationUUIDField;
        
        private string salesOrganisationIDField;
        
        private DistributionChannelCode distributionChannelCodeField;
        
        private ActionCode actionCodeField;
        
        private bool actionCodeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=0)]
        public string ObjectNodeSenderTechnicalID {
            get {
                return this.objectNodeSenderTechnicalIDField;
            }
            set {
                this.objectNodeSenderTechnicalIDField = value;
                this.RaisePropertyChanged("ObjectNodeSenderTechnicalID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public UUID SalesOrganisationUUID {
            get {
                return this.salesOrganisationUUIDField;
            }
            set {
                this.salesOrganisationUUIDField = value;
                this.RaisePropertyChanged("SalesOrganisationUUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=2)]
        public string SalesOrganisationID {
            get {
                return this.salesOrganisationIDField;
            }
            set {
                this.salesOrganisationIDField = value;
                this.RaisePropertyChanged("SalesOrganisationID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public DistributionChannelCode DistributionChannelCode {
            get {
                return this.distributionChannelCodeField;
            }
            set {
                this.distributionChannelCodeField = value;
                this.RaisePropertyChanged("DistributionChannelCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ActionCode actionCode {
            get {
                return this.actionCodeField;
            }
            set {
                this.actionCodeField = value;
                this.RaisePropertyChanged("actionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool actionCodeSpecified {
            get {
                return this.actionCodeFieldSpecified;
            }
            set {
                this.actionCodeFieldSpecified = value;
                this.RaisePropertyChanged("actionCodeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public enum ActionCode {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01")]
        Item01,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02")]
        Item02,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03")]
        Item03,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("04")]
        Item04,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("05")]
        Item05,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("06")]
        Item06,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/A1S/Global")]
    public partial class BusinessPartnerHierarchyMaintainRequestGroupBusinessPartner : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string objectNodeSenderTechnicalIDField;
        
        private UUID uUIDField;
        
        private string internalIDField;
        
        private ActionCode actionCodeField;
        
        private bool actionCodeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=0)]
        public string ObjectNodeSenderTechnicalID {
            get {
                return this.objectNodeSenderTechnicalIDField;
            }
            set {
                this.objectNodeSenderTechnicalIDField = value;
                this.RaisePropertyChanged("ObjectNodeSenderTechnicalID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public UUID UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
                this.RaisePropertyChanged("UUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=2)]
        public string InternalID {
            get {
                return this.internalIDField;
            }
            set {
                this.internalIDField = value;
                this.RaisePropertyChanged("InternalID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ActionCode actionCode {
            get {
                return this.actionCodeField;
            }
            set {
                this.actionCodeField = value;
                this.RaisePropertyChanged("actionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool actionCodeSpecified {
            get {
                return this.actionCodeFieldSpecified;
            }
            set {
                this.actionCodeFieldSpecified = value;
                this.RaisePropertyChanged("actionCodeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/A1S/Global")]
    public partial class BusinessPartnerHierarchyMaintainRequestGroup : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string objectNodeSenderTechnicalIDField;
        
        private UUID uUIDField;
        
        private string idField;
        
        private string nameField;
        
        private string noteField;
        
        private UUID parentGroupUUIDField;
        
        private string parentGroupIDField;
        
        private BusinessPartnerHierarchyMaintainRequestGroupBusinessPartner[] businessPartnerField;
        
        private BusinessPartnerHierarchyMaintainRequestGroupBusinessArea[] businessAreaField;
        
        private ActionCode actionCodeField;
        
        private bool actionCodeFieldSpecified;
        
        private bool businessPartnerListCompleteTransmissionIndicatorField;
        
        private bool businessPartnerListCompleteTransmissionIndicatorFieldSpecified;
        
        private bool businessAreaListCompleteTransmissionIndicatorField;
        
        private bool businessAreaListCompleteTransmissionIndicatorFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=0)]
        public string ObjectNodeSenderTechnicalID {
            get {
                return this.objectNodeSenderTechnicalIDField;
            }
            set {
                this.objectNodeSenderTechnicalIDField = value;
                this.RaisePropertyChanged("ObjectNodeSenderTechnicalID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public UUID UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
                this.RaisePropertyChanged("UUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=2)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
                this.RaisePropertyChanged("Note");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public UUID ParentGroupUUID {
            get {
                return this.parentGroupUUIDField;
            }
            set {
                this.parentGroupUUIDField = value;
                this.RaisePropertyChanged("ParentGroupUUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=6)]
        public string ParentGroupID {
            get {
                return this.parentGroupIDField;
            }
            set {
                this.parentGroupIDField = value;
                this.RaisePropertyChanged("ParentGroupID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BusinessPartner", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public BusinessPartnerHierarchyMaintainRequestGroupBusinessPartner[] BusinessPartner {
            get {
                return this.businessPartnerField;
            }
            set {
                this.businessPartnerField = value;
                this.RaisePropertyChanged("BusinessPartner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BusinessArea", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public BusinessPartnerHierarchyMaintainRequestGroupBusinessArea[] BusinessArea {
            get {
                return this.businessAreaField;
            }
            set {
                this.businessAreaField = value;
                this.RaisePropertyChanged("BusinessArea");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ActionCode actionCode {
            get {
                return this.actionCodeField;
            }
            set {
                this.actionCodeField = value;
                this.RaisePropertyChanged("actionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool actionCodeSpecified {
            get {
                return this.actionCodeFieldSpecified;
            }
            set {
                this.actionCodeFieldSpecified = value;
                this.RaisePropertyChanged("actionCodeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool businessPartnerListCompleteTransmissionIndicator {
            get {
                return this.businessPartnerListCompleteTransmissionIndicatorField;
            }
            set {
                this.businessPartnerListCompleteTransmissionIndicatorField = value;
                this.RaisePropertyChanged("businessPartnerListCompleteTransmissionIndicator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool businessPartnerListCompleteTransmissionIndicatorSpecified {
            get {
                return this.businessPartnerListCompleteTransmissionIndicatorFieldSpecified;
            }
            set {
                this.businessPartnerListCompleteTransmissionIndicatorFieldSpecified = value;
                this.RaisePropertyChanged("businessPartnerListCompleteTransmissionIndicatorSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool businessAreaListCompleteTransmissionIndicator {
            get {
                return this.businessAreaListCompleteTransmissionIndicatorField;
            }
            set {
                this.businessAreaListCompleteTransmissionIndicatorField = value;
                this.RaisePropertyChanged("businessAreaListCompleteTransmissionIndicator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool businessAreaListCompleteTransmissionIndicatorSpecified {
            get {
                return this.businessAreaListCompleteTransmissionIndicatorFieldSpecified;
            }
            set {
                this.businessAreaListCompleteTransmissionIndicatorFieldSpecified = value;
                this.RaisePropertyChanged("businessAreaListCompleteTransmissionIndicatorSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/A1S/Global")]
    public partial class BusinessPartnerHierarchyMaintainRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string objectNodeSenderTechnicalIDField;
        
        private string changeStateIDField;
        
        private UUID uUIDField;
        
        private BusinessPartnerHierarchyID idField;
        
        private string nameField;
        
        private BusinessPartnerHierarchyMaintainRequestGroup[] groupField;
        
        private ActionCode actionCodeField;
        
        private bool actionCodeFieldSpecified;
        
        private bool groupListCompleteTransmissionIndicatorField;
        
        private bool groupListCompleteTransmissionIndicatorFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=0)]
        public string ObjectNodeSenderTechnicalID {
            get {
                return this.objectNodeSenderTechnicalIDField;
            }
            set {
                this.objectNodeSenderTechnicalIDField = value;
                this.RaisePropertyChanged("ObjectNodeSenderTechnicalID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=1)]
        public string ChangeStateID {
            get {
                return this.changeStateIDField;
            }
            set {
                this.changeStateIDField = value;
                this.RaisePropertyChanged("ChangeStateID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public UUID UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
                this.RaisePropertyChanged("UUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public BusinessPartnerHierarchyID ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Group", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public BusinessPartnerHierarchyMaintainRequestGroup[] Group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
                this.RaisePropertyChanged("Group");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ActionCode actionCode {
            get {
                return this.actionCodeField;
            }
            set {
                this.actionCodeField = value;
                this.RaisePropertyChanged("actionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool actionCodeSpecified {
            get {
                return this.actionCodeFieldSpecified;
            }
            set {
                this.actionCodeFieldSpecified = value;
                this.RaisePropertyChanged("actionCodeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool groupListCompleteTransmissionIndicator {
            get {
                return this.groupListCompleteTransmissionIndicatorField;
            }
            set {
                this.groupListCompleteTransmissionIndicatorField = value;
                this.RaisePropertyChanged("groupListCompleteTransmissionIndicator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool groupListCompleteTransmissionIndicatorSpecified {
            get {
                return this.groupListCompleteTransmissionIndicatorFieldSpecified;
            }
            set {
                this.groupListCompleteTransmissionIndicatorFieldSpecified = value;
                this.RaisePropertyChanged("groupListCompleteTransmissionIndicatorSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public partial class BusinessDocumentMessageID : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string schemeIDField;
        
        private string schemeAgencyIDField;
        
        private AgencyIdentificationCode schemeAgencySchemeAgencyIDField;
        
        private bool schemeAgencySchemeAgencyIDFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeID {
            get {
                return this.schemeIDField;
            }
            set {
                this.schemeIDField = value;
                this.RaisePropertyChanged("schemeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeAgencyID {
            get {
                return this.schemeAgencyIDField;
            }
            set {
                this.schemeAgencyIDField = value;
                this.RaisePropertyChanged("schemeAgencyID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AgencyIdentificationCode schemeAgencySchemeAgencyID {
            get {
                return this.schemeAgencySchemeAgencyIDField;
            }
            set {
                this.schemeAgencySchemeAgencyIDField = value;
                this.RaisePropertyChanged("schemeAgencySchemeAgencyID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool schemeAgencySchemeAgencyIDSpecified {
            get {
                return this.schemeAgencySchemeAgencyIDFieldSpecified;
            }
            set {
                this.schemeAgencySchemeAgencyIDFieldSpecified = value;
                this.RaisePropertyChanged("schemeAgencySchemeAgencyIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public partial class BusinessDocumentBasicMessageHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BusinessDocumentMessageID idField;
        
        private UUID uUIDField;
        
        private BusinessDocumentMessageID referenceIDField;
        
        private UUID referenceUUIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public BusinessDocumentMessageID ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public UUID UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
                this.RaisePropertyChanged("UUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public BusinessDocumentMessageID ReferenceID {
            get {
                return this.referenceIDField;
            }
            set {
                this.referenceIDField = value;
                this.RaisePropertyChanged("ReferenceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public UUID ReferenceUUID {
            get {
                return this.referenceUUIDField;
            }
            set {
                this.referenceUUIDField = value;
                this.RaisePropertyChanged("ReferenceUUID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/A1S/Global")]
    public partial class BusinessPartnerHierarchyMaintainRequestMessage_sync : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BusinessDocumentBasicMessageHeader basicMessageHeaderField;
        
        private BusinessPartnerHierarchyMaintainRequest[] businessPartnerHierarchyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public BusinessDocumentBasicMessageHeader BasicMessageHeader {
            get {
                return this.basicMessageHeaderField;
            }
            set {
                this.basicMessageHeaderField = value;
                this.RaisePropertyChanged("BasicMessageHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BusinessPartnerHierarchy", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public BusinessPartnerHierarchyMaintainRequest[] BusinessPartnerHierarchy {
            get {
                return this.businessPartnerHierarchyField;
            }
            set {
                this.businessPartnerHierarchyField = value;
                this.RaisePropertyChanged("BusinessPartnerHierarchy");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sap.com/xi/A1S/Global", ConfigurationName="AccountHierarchyManageService.ManageBusinessPartnerHierarchyIn")]
    public interface ManageBusinessPartnerHierarchyIn {
        
        // CODEGEN: Generating message contract since the operation MaintainBundle is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/A1S/Global/ManageBusinessPartnerHierarchyIn/MaintainBundleReque" +
            "st", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sourceportal.SAP.Services.AccountHierarchyManageService.StandardFaultMessage), Action="http://sap.com/xi/A1S/Global/ManageBusinessPartnerHierarchyIn/MaintainBundleReque" +
            "st", Name="StandardFaultMessage", Namespace="http://sap.com/xi/AP/Common/Global")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sourceportal.SAP.Services.AccountHierarchyManageService.MaintainBundleResponse MaintainBundle(Sourceportal.SAP.Services.AccountHierarchyManageService.MaintainBundleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/A1S/Global/ManageBusinessPartnerHierarchyIn/MaintainBundleReque" +
            "st", ReplyAction="*")]
        System.Threading.Tasks.Task<Sourceportal.SAP.Services.AccountHierarchyManageService.MaintainBundleResponse> MaintainBundleAsync(Sourceportal.SAP.Services.AccountHierarchyManageService.MaintainBundleRequest request);
        
        // CODEGEN: Generating message contract since the operation CheckMaintainBundle is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/A1S/Global/ManageBusinessPartnerHierarchyIn/CheckMaintainBundle" +
            "Request", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sourceportal.SAP.Services.AccountHierarchyManageService.StandardFaultMessage), Action="http://sap.com/xi/A1S/Global/ManageBusinessPartnerHierarchyIn/CheckMaintainBundle" +
            "Request", Name="StandardFaultMessage", Namespace="http://sap.com/xi/AP/Common/Global")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sourceportal.SAP.Services.AccountHierarchyManageService.CheckMaintainBundleResponse CheckMaintainBundle(Sourceportal.SAP.Services.AccountHierarchyManageService.CheckMaintainBundleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/A1S/Global/ManageBusinessPartnerHierarchyIn/CheckMaintainBundle" +
            "Request", ReplyAction="*")]
        System.Threading.Tasks.Task<Sourceportal.SAP.Services.AccountHierarchyManageService.CheckMaintainBundleResponse> CheckMaintainBundleAsync(Sourceportal.SAP.Services.AccountHierarchyManageService.CheckMaintainBundleRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MaintainBundleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sap.com/xi/SAPGlobal20/Global", Order=0)]
        public Sourceportal.SAP.Services.AccountHierarchyManageService.BusinessPartnerHierarchyMaintainRequestMessage_sync BusinessPartnerHierarchyBundleMaintainRequest_sync;
        
        public MaintainBundleRequest() {
        }
        
        public MaintainBundleRequest(Sourceportal.SAP.Services.AccountHierarchyManageService.BusinessPartnerHierarchyMaintainRequestMessage_sync BusinessPartnerHierarchyBundleMaintainRequest_sync) {
            this.BusinessPartnerHierarchyBundleMaintainRequest_sync = BusinessPartnerHierarchyBundleMaintainRequest_sync;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MaintainBundleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sap.com/xi/SAPGlobal20/Global", Order=0)]
        public Sourceportal.SAP.Services.AccountHierarchyManageService.BusinessPartnerHierarchyMaintainConfirmationMessage_sync BusinessPartnerHierarchyBundleMaintainConfirmation_sync;
        
        public MaintainBundleResponse() {
        }
        
        public MaintainBundleResponse(Sourceportal.SAP.Services.AccountHierarchyManageService.BusinessPartnerHierarchyMaintainConfirmationMessage_sync BusinessPartnerHierarchyBundleMaintainConfirmation_sync) {
            this.BusinessPartnerHierarchyBundleMaintainConfirmation_sync = BusinessPartnerHierarchyBundleMaintainConfirmation_sync;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckMaintainBundleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sap.com/xi/SAPGlobal20/Global", Order=0)]
        public Sourceportal.SAP.Services.AccountHierarchyManageService.BusinessPartnerHierarchyMaintainRequestMessage_sync BusinessPartnerHierarchyBundleMaintenanceCheckRequest_sync;
        
        public CheckMaintainBundleRequest() {
        }
        
        public CheckMaintainBundleRequest(Sourceportal.SAP.Services.AccountHierarchyManageService.BusinessPartnerHierarchyMaintainRequestMessage_sync BusinessPartnerHierarchyBundleMaintenanceCheckRequest_sync) {
            this.BusinessPartnerHierarchyBundleMaintenanceCheckRequest_sync = BusinessPartnerHierarchyBundleMaintenanceCheckRequest_sync;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckMaintainBundleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sap.com/xi/SAPGlobal20/Global", Order=0)]
        public Sourceportal.SAP.Services.AccountHierarchyManageService.BusinessPartnerHierarchyMaintainConfirmationMessage_sync BusinessPartnerHierarchyBundleMaintenanceCheckConfirmation_sync;
        
        public CheckMaintainBundleResponse() {
        }
        
        public CheckMaintainBundleResponse(Sourceportal.SAP.Services.AccountHierarchyManageService.BusinessPartnerHierarchyMaintainConfirmationMessage_sync BusinessPartnerHierarchyBundleMaintenanceCheckConfirmation_sync) {
            this.BusinessPartnerHierarchyBundleMaintenanceCheckConfirmation_sync = BusinessPartnerHierarchyBundleMaintenanceCheckConfirmation_sync;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ManageBusinessPartnerHierarchyInChannel : Sourceportal.SAP.Services.AccountHierarchyManageService.ManageBusinessPartnerHierarchyIn, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ManageBusinessPartnerHierarchyInClient : System.ServiceModel.ClientBase<Sourceportal.SAP.Services.AccountHierarchyManageService.ManageBusinessPartnerHierarchyIn>, Sourceportal.SAP.Services.AccountHierarchyManageService.ManageBusinessPartnerHierarchyIn {
        
        public ManageBusinessPartnerHierarchyInClient() {
        }
        
        public ManageBusinessPartnerHierarchyInClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ManageBusinessPartnerHierarchyInClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManageBusinessPartnerHierarchyInClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManageBusinessPartnerHierarchyInClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sourceportal.SAP.Services.AccountHierarchyManageService.MaintainBundleResponse Sourceportal.SAP.Services.AccountHierarchyManageService.ManageBusinessPartnerHierarchyIn.MaintainBundle(Sourceportal.SAP.Services.AccountHierarchyManageService.MaintainBundleRequest request) {
            return base.Channel.MaintainBundle(request);
        }
        
        public Sourceportal.SAP.Services.AccountHierarchyManageService.BusinessPartnerHierarchyMaintainConfirmationMessage_sync MaintainBundle(Sourceportal.SAP.Services.AccountHierarchyManageService.BusinessPartnerHierarchyMaintainRequestMessage_sync BusinessPartnerHierarchyBundleMaintainRequest_sync) {
            Sourceportal.SAP.Services.AccountHierarchyManageService.MaintainBundleRequest inValue = new Sourceportal.SAP.Services.AccountHierarchyManageService.MaintainBundleRequest();
            inValue.BusinessPartnerHierarchyBundleMaintainRequest_sync = BusinessPartnerHierarchyBundleMaintainRequest_sync;
            Sourceportal.SAP.Services.AccountHierarchyManageService.MaintainBundleResponse retVal = ((Sourceportal.SAP.Services.AccountHierarchyManageService.ManageBusinessPartnerHierarchyIn)(this)).MaintainBundle(inValue);
            return retVal.BusinessPartnerHierarchyBundleMaintainConfirmation_sync;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Sourceportal.SAP.Services.AccountHierarchyManageService.MaintainBundleResponse> Sourceportal.SAP.Services.AccountHierarchyManageService.ManageBusinessPartnerHierarchyIn.MaintainBundleAsync(Sourceportal.SAP.Services.AccountHierarchyManageService.MaintainBundleRequest request) {
            return base.Channel.MaintainBundleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Sourceportal.SAP.Services.AccountHierarchyManageService.MaintainBundleResponse> MaintainBundleAsync(Sourceportal.SAP.Services.AccountHierarchyManageService.BusinessPartnerHierarchyMaintainRequestMessage_sync BusinessPartnerHierarchyBundleMaintainRequest_sync) {
            Sourceportal.SAP.Services.AccountHierarchyManageService.MaintainBundleRequest inValue = new Sourceportal.SAP.Services.AccountHierarchyManageService.MaintainBundleRequest();
            inValue.BusinessPartnerHierarchyBundleMaintainRequest_sync = BusinessPartnerHierarchyBundleMaintainRequest_sync;
            return ((Sourceportal.SAP.Services.AccountHierarchyManageService.ManageBusinessPartnerHierarchyIn)(this)).MaintainBundleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sourceportal.SAP.Services.AccountHierarchyManageService.CheckMaintainBundleResponse Sourceportal.SAP.Services.AccountHierarchyManageService.ManageBusinessPartnerHierarchyIn.CheckMaintainBundle(Sourceportal.SAP.Services.AccountHierarchyManageService.CheckMaintainBundleRequest request) {
            return base.Channel.CheckMaintainBundle(request);
        }
        
        public Sourceportal.SAP.Services.AccountHierarchyManageService.BusinessPartnerHierarchyMaintainConfirmationMessage_sync CheckMaintainBundle(Sourceportal.SAP.Services.AccountHierarchyManageService.BusinessPartnerHierarchyMaintainRequestMessage_sync BusinessPartnerHierarchyBundleMaintenanceCheckRequest_sync) {
            Sourceportal.SAP.Services.AccountHierarchyManageService.CheckMaintainBundleRequest inValue = new Sourceportal.SAP.Services.AccountHierarchyManageService.CheckMaintainBundleRequest();
            inValue.BusinessPartnerHierarchyBundleMaintenanceCheckRequest_sync = BusinessPartnerHierarchyBundleMaintenanceCheckRequest_sync;
            Sourceportal.SAP.Services.AccountHierarchyManageService.CheckMaintainBundleResponse retVal = ((Sourceportal.SAP.Services.AccountHierarchyManageService.ManageBusinessPartnerHierarchyIn)(this)).CheckMaintainBundle(inValue);
            return retVal.BusinessPartnerHierarchyBundleMaintenanceCheckConfirmation_sync;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Sourceportal.SAP.Services.AccountHierarchyManageService.CheckMaintainBundleResponse> Sourceportal.SAP.Services.AccountHierarchyManageService.ManageBusinessPartnerHierarchyIn.CheckMaintainBundleAsync(Sourceportal.SAP.Services.AccountHierarchyManageService.CheckMaintainBundleRequest request) {
            return base.Channel.CheckMaintainBundleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Sourceportal.SAP.Services.AccountHierarchyManageService.CheckMaintainBundleResponse> CheckMaintainBundleAsync(Sourceportal.SAP.Services.AccountHierarchyManageService.BusinessPartnerHierarchyMaintainRequestMessage_sync BusinessPartnerHierarchyBundleMaintenanceCheckRequest_sync) {
            Sourceportal.SAP.Services.AccountHierarchyManageService.CheckMaintainBundleRequest inValue = new Sourceportal.SAP.Services.AccountHierarchyManageService.CheckMaintainBundleRequest();
            inValue.BusinessPartnerHierarchyBundleMaintenanceCheckRequest_sync = BusinessPartnerHierarchyBundleMaintenanceCheckRequest_sync;
            return ((Sourceportal.SAP.Services.AccountHierarchyManageService.ManageBusinessPartnerHierarchyIn)(this)).CheckMaintainBundleAsync(inValue);
        }
    }
}
